// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show kIsWeb, defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Platform      FirebaseOptions
/// web           webOptions
/// android       androidOptions
/// ios           iosOptions
/// macos         macosOptions
/// windows       No options currently available; you can use the default options.
/// linux         No options currently available; you can use the default options.
///
/// For example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClx9BlGzXGvlS0j6zfetr-OKnAgJFKLjA',
    appId: '1:549481141467:web:db6b0331f9924f77a8a8fe',
    messagingSenderId: '549481141467',
    projectId: 'svendeprojekt-c3234',
    authDomain: 'svendeprojekt-c3234.firebaseapp.com',
    storageBucket: 'svendeprojekt-c3234.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv6CCCF0hi2p5tzOUbzTLhEgLeRWFnKls',
    appId: '1:549481141467:android:3258612cfc936e6ba8a8fe',
    messagingSenderId: '549481141467',
    projectId: 'svendeprojekt-c3234',
    storageBucket: 'svendeprojekt-c3234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtXd7X4h005ywNott58ZCLFicsPG1Dbig',
    appId: '1:549481141467:ios:cb7df7c0b5b77539a8a8fe',
    messagingSenderId: '549481141467',
    projectId: 'svendeprojekt-c3234',
    storageBucket: 'svendeprojekt-c3234.firebasestorage.app',
    iosClientId:
        '549481141467-7cjkoe10k0d0j75l2l5gg639avqgpafe.apps.googleusercontent.com',
    iosBundleId: 'com.example.ccApp',
  );
}
